spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: "test"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_LOWER=true
    username: sa
    password: 1
  h2:
    console:
      enabled: true
      path: /h2