spring:
  liquibase:
    change-log: db/changelog/master.yml
    enabled: true
    contexts: "test"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
